"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, Cloud, CloudOff, Download, FileText, FileUp, Filter, LayoutList, Menu, Plus, RefreshCw, Search, Settings, Star, Tags, Upload, Users, X } from "lucide-react";
import { repository } from "@/data/repository";
import { Category, Filters, Holiday, Meeting, MeetingTask, View } from "@/types";
import { eventToMeeting, parseIcs } from "@/data/ics";
import { compareMeetings } from "@/lib/date";
import { DATA_FILE_NAME, DRIVE_FOLDER_ID } from "@/data/googleDrive";
import { DriveStatus, useDriveSync } from "@/data/useDriveSync";
import MeetingCard from "./MeetingCard";
import MeetingPanel from "./MeetingPanel";
import MeetingForm from "./MeetingForm";
import Logo from "./Logo";
import CalendarView from "./CalendarView";

const blankFilters:Filters={category:"",place:"",from:"",to:"",important:false,hasTasks:false,incomplete:false};
const nav=[
  ["all","すべて",LayoutList],["today","今日",CalendarDays],["week","今週",Clock3],["tasks","自分のタスク",CheckCircle2],
  ["incomplete","未完了タスク",CircleAlert],["important","重要",Star],["categories","分類",Tags],["settings","設定",Settings]
] as const;
const localDate=(d=new Date())=>{const o=d.getTimezoneOffset(); return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};

export default function MeetingHub(){
  const [meetings,setMeetings]=useState<Meeting[]>([]),[categories,setCategories]=useState<Category[]>([]),[holidays,setHolidays]=useState<Holiday[]>([]),[ready,setReady]=useState(false);
  const [view,setView]=useState<View>("all"),[query,setQuery]=useState(""),[filters,setFilters]=useState(blankFilters),[filterOpen,setFilterOpen]=useState(false),[sidebar,setSidebar]=useState(false);
  const [selected,setSelected]=useState<Meeting|null>(null),[editing,setEditing]=useState<Meeting|null|undefined>(undefined);
  const fileRef=useRef<HTMLInputElement>(null),csvRef=useRef<HTMLInputElement>(null),icsRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{setMeetings(repository.loadMeetings());setCategories(repository.loadCategories());setHolidays(repository.loadHolidays());setReady(true)},[]);
  useEffect(()=>{if(ready) repository.saveMeetings(meetings)},[meetings,ready]);
  useEffect(()=>{if(ready) repository.saveCategories(categories)},[categories,ready]);
  useEffect(()=>{if(ready) repository.saveHolidays(holidays)},[holidays,ready]);
  const snapshot=useMemo(()=>JSON.stringify([meetings,categories,holidays]),[meetings,categories,holidays]);
  const sync=useDriveSync({ready,snapshot,serialize:()=>repository.exportData(meetings,categories,holidays),apply:raw=>{const d=repository.parseImport(raw);setMeetings(d.meetings);setCategories(d.categories);setHolidays(d.holidays);return JSON.stringify([d.meetings,d.categories,d.holidays])}});
  const today=localDate(); const weekStart=(()=>{const d=new Date(today+"T12:00:00");d.setDate(d.getDate()-((d.getDay()+6)%7));return localDate(d)})(); const weekEnd=(()=>{const d=new Date(weekStart+"T12:00:00");d.setDate(d.getDate()+6);return localDate(d)})();
  const visible=useMemo(()=>meetings.filter(m=>{
    const hay=[m.title,m.memo,m.category,...m.tags,...m.tasks.map(t=>t.title)].join(" ").toLowerCase();
    const q=!query||hay.includes(query.toLowerCase()); const v=view==="all"||view==="categories"||view==="settings"||view==="tasks"||view==="today"&&m.date===today||view==="week"&&m.date>=weekStart&&m.date<=weekEnd||view==="important"&&m.important||view==="incomplete"&&m.tasks.some(t=>!t.completed);
    return q&&v&&(!filters.category||m.category===filters.category)&&(!filters.place||m.place===filters.place)&&(!filters.from||m.date>=filters.from)&&(!filters.to||m.date<=filters.to)&&(!filters.important||m.important)&&(!filters.hasTasks||m.tasks.length>0)&&(!filters.incomplete||m.tasks.some(t=>!t.completed));
  }).sort((a,b)=>compareMeetings(b,a)),[meetings,query,filters,view,today,weekStart,weekEnd]);
  const incomplete=meetings.flatMap(m=>m.tasks).filter(t=>!t.completed).length, weekly=meetings.filter(m=>m.date>=weekStart&&m.date<=weekEnd).length, important=meetings.filter(m=>m.important).length;
  const save=(m:Meeting)=>{setMeetings(x=>x.some(i=>i.id===m.id)?x.map(i=>i.id===m.id?m:i):[m,...x]);setEditing(undefined);setSelected(m)};
  const remove=(id:string)=>{if(confirm("この会議を削除しますか？")){setMeetings(x=>x.filter(m=>m.id!==id));setSelected(null)}};
  const toggleTask=(mid:string,tid:string)=>setMeetings(x=>x.map(m=>m.id===mid?{...m,tasks:m.tasks.map(t=>t.id===tid?{...t,completed:!t.completed}:t),updatedAt:new Date().toISOString()}:m));
  const download=()=>{const blob=new Blob([repository.exportData(meetings,categories,holidays)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`meeting-hub-${today}.json`;a.click();URL.revokeObjectURL(a.href)};
  const importCsv=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=repository.parseCsv(await f.text(),categories);setMeetings(x=>[...d.meetings,...x]);setCategories(d.categories);alert(`${d.meetings.length}件を取り込みました`)}catch{alert("CSVを読み込めませんでした")}e.target.value=""};
  const importJson=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=repository.parseImport(await f.text());setMeetings(d.meetings);setCategories(d.categories);setHolidays(d.holidays);alert("データを復元しました") }catch{alert("有効なMeeting HubのJSONファイルを選択してください") }e.target.value=""};
  const importIcs=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value="";if(!f)return;
    const events=parseIcs(await f.text());if(!events.length){alert("ICSファイルに予定が見つかりませんでした");return}
    const fresh=events.filter(ev=>!meetings.some(m=>m.icsUid===ev.uid)),dup=events.length-fresh.length;
    if(events.length===1){const existing=meetings.find(m=>m.icsUid===events[0].uid);if(existing&&!confirm("この予定は登録済みです。もう一度追加しますか？")){setSelected(existing);return}setEditing(eventToMeeting(events[0],categories));return}
    if(!fresh.length){alert(`${events.length}件すべて登録済みです`);return}
    if(confirm(`${fresh.length}件の予定を追加します。${dup?`（登録済みの${dup}件は除外）`:""}`))setMeetings(x=>[...fresh.map(ev=>eventToMeeting(ev,categories)),...x]);};
  const selectedDay=filters.from&&filters.from===filters.to?filters.from:"";
  const selectDay=(date:string)=>{if(date===selectedDay){setFilters({...filters,from:"",to:""});return}setFilters({...filters,from:date,to:date});if(view==="tasks"||view==="settings")setView("all")};
  const activeFilters=Object.values(filters).filter(Boolean).length;
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?"open":""}`}><div className="brand"><span className="brand-mark"><Logo/></span><span>Meeting Hub</span><button className="mobile-close" onClick={()=>setSidebar(false)}><X/></button></div><nav>{nav.map(([id,label,Icon],i)=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setSidebar(false)}}><Icon size={19}/><span>{label}</span>{id==="incomplete"&&incomplete>0&&<b>{incomplete}</b>}{i===2&&<span className="nav-rule"/>}</button>)}</nav><div className="sidebar-foot"><DriveBadge status={sync.status} onClick={()=>{setView("settings");setSidebar(false)}}/></div></aside>
    <main><header><button className="menu-btn" onClick={()=>setSidebar(true)}><Menu/></button><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="会議、メモ、タスクを検索..."/><kbd>⌘ K</kbd></div><div className="header-actions"><button className={`button secondary ${filterOpen?"selected":""}`} onClick={()=>setFilterOpen(!filterOpen)}><Filter size={17}/>フィルター{activeFilters>0&&<i>{activeFilters}</i>}</button><button className="button secondary" onClick={()=>icsRef.current?.click()} title="Outlook・Teams の予定（.ics）から会議を追加"><FileUp size={17}/>ICSから追加</button><button className="button primary" onClick={()=>setEditing(null)}><Plus size={18}/>会議を追加</button></div></header>
      <div className="content">{!["saved","syncing","connecting"].includes(sync.status)&&<DriveNotice status={sync.status} message={sync.message} onConnect={sync.connect}/>}<div className="page-title"><div><p className="eyebrow">WORKSPACE / MEETINGS</p><h1>{view==="tasks"?"自分のタスク":view==="today"?"今日の会議":view==="week"?"今週の会議":view==="important"?"重要な会議":view==="incomplete"?"未完了タスクのある会議":"会議一覧"}</h1><p>{view==="tasks"?"すべての会議から、あなたのアクションを集約しています。":"会議の記録、関連資料、次のアクションをひとつの場所に。"}</p></div><span className="date-chip"><CalendarDays size={15}/>{new Intl.DateTimeFormat("ja-JP",{month:"long",day:"numeric",weekday:"short"}).format(new Date())}</span></div>
      {filterOpen&&<FilterBar filters={filters} setFilters={setFilters} categories={categories}/>} 
      <section className="summaries"><Summary label="今週の会議" value={weekly} icon={<CalendarDays/>} tone="blue" onClick={()=>setView("week")}/><Summary label="未完了タスク" value={incomplete} icon={<CircleAlert/>} tone="amber" onClick={()=>setView("incomplete")}/><Summary label="重要" value={important} icon={<Star/>} tone="rose" onClick={()=>setView("important")}/></section>
      <CalendarView meetings={meetings} holidays={holidays} today={today} setHolidays={setHolidays} onOpen={setSelected} selectedDay={selectedDay} onSelectDay={selectDay}/>
      {view==="tasks"?<TaskView meetings={meetings} toggle={toggleTask} open={setSelected}/>:view==="settings"?<SettingsView sync={sync} meetings={meetings} categories={categories} setCategories={setCategories} download={download} fileRef={fileRef} csvRef={csvRef}/>:<section className="list-section"><div className="list-head"><div><h2>{selectedDay?"選択した日の会議":view==="all"?"最近の会議":"該当する会議"}</h2><span>{visible.length}件</span>{selectedDay&&<button className="day-chip" onClick={()=>selectDay(selectedDay)} title="日付の絞り込みを解除">{Number(selectedDay.slice(5,7))}/{Number(selectedDay.slice(8))}<X/></button>}</div><button className="sort">日付順 <ChevronRight size={15}/></button></div><div className="meeting-list">{visible.map(m=><MeetingCard key={m.id} meeting={m} category={categories.find(c=>c.id===m.category)} onClick={()=>setSelected(m)}/>)}{visible.length===0&&<div className="empty"><Search/><h3>会議が見つかりません</h3><p>検索語やフィルター条件を変更してください。</p></div>}</div></section>}
      </div>
    </main>
    {selected&&<MeetingPanel meeting={meetings.find(m=>m.id===selected.id)??selected} category={categories.find(c=>c.id===selected.category)} onClose={()=>setSelected(null)} onEdit={m=>setEditing(m)} onDelete={remove} onToggleTask={tid=>toggleTask(selected.id,tid)}/>} 
    {editing!==undefined&&<MeetingForm meeting={editing} isNew={!editing||!meetings.some(m=>m.id===editing.id)} categories={categories} onClose={()=>setEditing(undefined)} onSave={save}/>} 
    <input hidden type="file" accept="application/json" ref={fileRef} onChange={importJson}/>
    <input hidden type="file" accept=".csv,text/csv" ref={csvRef} onChange={importCsv}/>
    <input hidden type="file" accept=".ics,text/calendar" ref={icsRef} onChange={importIcs}/>
  </div>
}
function Summary({label,value,icon,tone,onClick}:{label:string;value:number;icon:React.ReactNode;tone:string;onClick:()=>void}){return <button className="summary" onClick={onClick}><span className={`summary-icon ${tone}`}>{icon}</span><span><small>{label}</small><strong>{value}</strong></span><ChevronRight/></button>}
function FilterBar({filters,setFilters,categories}:{filters:Filters;setFilters:(f:Filters)=>void;categories:Category[]}){return <div className="filter-bar"><label>期間<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><span>〜</span><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">すべての分類</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={filters.place} onChange={e=>setFilters({...filters,place:e.target.value})}><option value="">すべての場所</option><option>Teams</option><option>対面</option><option>その他</option></select>{[["important","重要のみ"],["hasTasks","タスクあり"],["incomplete","未完了あり"]].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={Boolean(filters[k as keyof Filters])} onChange={e=>setFilters({...filters,[k]:e.target.checked})}/>{l}</label>)}<button onClick={()=>setFilters(blankFilters)}>クリア</button></div>}
function TaskView({meetings,toggle,open}:{meetings:Meeting[];toggle:(m:string,t:string)=>void;open:(m:Meeting)=>void}){const rows=meetings.flatMap(m=>m.tasks.map(t=>({m,t})));return <section className="task-board">{[false,true].map(done=><div key={String(done)}><div className="task-title"><h2>{done?"完了":"未完了"}</h2><span>{rows.filter(x=>x.t.completed===done).length}</span></div>{rows.filter(x=>x.t.completed===done).map(({m,t})=><div className={`task-row ${done?"done":""}`} key={t.id}><button className="task-check" onClick={()=>toggle(m.id,t.id)}>{t.completed?<CheckCircle2/>:<span/>}</button><button className="task-main" onClick={()=>open(m)}><strong>{t.title}</strong><small>{m.date.slice(5).replace("-","/")} ・ {m.title}{t.dueDate&&`　期限 ${t.dueDate.slice(5).replace("-","/")}`}</small></button><ChevronRight/></div>)}</div>)}</section>}
function SettingsView({sync,meetings,categories,setCategories,download,fileRef,csvRef}:{sync:ReturnType<typeof useDriveSync>;meetings:Meeting[];categories:Category[];setCategories:(c:Category[])=>void;download:()=>void;fileRef:React.RefObject<HTMLInputElement|null>;csvRef:React.RefObject<HTMLInputElement|null>}){const [name,setName]=useState("");return <section className="settings-card"><h2>設定・データ管理</h2><p>保存先の Google Drive、分類、バックアップを管理できます。</p><h3>保存先（Google Drive）</h3><div className="drive-card"><div className="drive-info"><DriveBadge status={sync.status}/><dl><dt>フォルダ</dt><dd><a href={`https://drive.google.com/drive/folders/${DRIVE_FOLDER_ID}`} target="_blank" rel="noreferrer">{sync.folderName||"保存先フォルダ"}</a> <code>{DRIVE_FOLDER_ID}</code></dd><dt>ファイル</dt><dd><code>{DATA_FILE_NAME}</code></dd>{sync.lastSynced&&<><dt>最終同期</dt><dd>{new Date(sync.lastSynced).toLocaleString("ja-JP")}</dd></>}</dl>{sync.message&&<p className="drive-error">{sync.message}</p>}</div><div className="drive-actions">{sync.status==="unconfigured"?<span className="muted">README の手順で <code>NEXT_PUBLIC_GOOGLE_CLIENT_ID</code> を設定してください</span>:sync.status==="disconnected"?<button className="button primary" onClick={sync.connect}><Cloud size={17}/>Google Drive に接続</button>:<><button className="button secondary" onClick={()=>void sync.syncNow()} disabled={sync.status==="syncing"||sync.status==="connecting"}><RefreshCw size={16}/>今すぐ同期</button><button className="button secondary" onClick={sync.disconnect}><CloudOff size={16}/>接続を解除</button></>}</div></div><h3>分類</h3><div className="category-settings">{categories.map(c=><span key={c.id}>{c.name}<button aria-label="削除" onClick={()=>setCategories(categories.filter(x=>x.id!==c.id))}>×</button></span>)}</div><div className="add-category"><input placeholder="新しい分類名" value={name} onChange={e=>setName(e.target.value)}/><button className="button primary" onClick={()=>{if(name.trim()){setCategories([...categories,{id:crypto.randomUUID(),name:name.trim(),color:"blue"}]);setName("")}}}><Plus size={17}/>追加</button></div><h3>バックアップ</h3><div className="backup-actions"><button className="button secondary" onClick={()=>csvRef.current?.click()}><Upload size={17}/>CSVインポート</button><button className="button secondary" onClick={download}><Download size={17}/>JSONエクスポート</button><button className="button secondary" onClick={()=>fileRef.current?.click()}><Upload size={17}/>JSONインポート</button><span>{meetings.length}件の会議を保存中</span></div></section>}
const DRIVE_LABEL:Record<DriveStatus,string>={unconfigured:"Drive 未設定",disconnected:"Drive 未接続",connecting:"接続中…",syncing:"保存中…",saved:"Google Drive に保存済み",reauth:"再接続が必要です",error:"同期エラー"};
function DriveBadge({status,onClick}:{status:DriveStatus;onClick?:()=>void}){const Icon=status==="saved"?Cloud:status==="syncing"||status==="connecting"?RefreshCw:CloudOff;const body=<><span className={`drive-dot ${status}`}><Icon size={16}/></span><span><strong>{DRIVE_LABEL[status]}</strong><small>{status==="saved"||status==="syncing"?"自動保存がオンです":"データはこのブラウザ内にあります"}</small></span></>;return onClick?<button className="drive-badge" onClick={onClick}>{body}</button>:<div className="drive-badge">{body}</div>}
function DriveNotice({status,message,onConnect}:{status:DriveStatus;message:string;onConnect:()=>void}){if(status==="unconfigured")return <div className="drive-notice"><CloudOff size={18}/><span><strong>Google Drive 保存が未設定です。</strong>データは現在このブラウザ内にのみ保存されています（設定手順は README を参照）。</span></div>;return <div className={`drive-notice ${status}`}><CloudOff size={18}/><span><strong>{status==="error"?"Google Drive への保存に失敗しました。":status==="reauth"?"Google Drive への再接続が必要です。":"データを Google Drive に保存するには接続してください。"}</strong>{message&&status!=="reauth"?` ${message}`:" 未保存の変更はこのブラウザに保持され、接続後に保存されます。"}</span><button className="button primary" onClick={onConnect}><Cloud size={16}/>{status==="disconnected"?"接続":"再接続"}</button></div>}
