import { FormEvent, useState } from "react";
import { Check, Plus, Trash2, X } from "lucide-react";
import { Category, LinkType, Meeting, MeetingLink, MeetingTask, Place } from "@/types";
const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
export default function MeetingForm({meeting,categories,onClose,onSave}:{meeting:Meeting|null;categories:Category[];onClose:()=>void;onSave:(m:Meeting)=>void}){
 const [date,setDate]=useState(meeting?.date??today()),[place,setPlace]=useState<Place>(meeting?.place??"Teams"),[category,setCategory]=useState(meeting?.category??categories[0]?.id??"other"),[title,setTitle]=useState(meeting?.title??""),[important,setImportant]=useState(meeting?.important??false),[memo,setMemo]=useState(meeting?.memo??""),[tags,setTags]=useState(meeting?.tags.join(", ")??"");
 const [links,setLinks]=useState<MeetingLink[]>(meeting?.links??[]),[tasks,setTasks]=useState<MeetingTask[]>(meeting?.tasks??[]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!title.trim())return;const now=new Date().toISOString();onSave({id:meeting?.id??crypto.randomUUID(),date,place,category,title:title.trim(),important,memo,tags:tags.split(/[,、]/).map(x=>x.trim()).filter(Boolean),links:links.filter(l=>l.title&&l.url),tasks:tasks.filter(t=>t.title),createdAt:meeting?.createdAt??now,updatedAt:now})};
 return <div className="overlay form-overlay"><form className="meeting-form" onSubmit={submit}><div className="panel-top"><span>{meeting?"会議を編集":"新しい会議"}</span><button type="button" onClick={onClose}><X/></button></div><div className="form-body"><p className="form-intro">会議の基本情報を入力してください。リンクやタスクは後から追加できます。</p><div className="form-grid"><label><span>日付 *</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>場所 *</span><select value={place} onChange={e=>setPlace(e.target.value as Place)}><option>Teams</option><option>対面</option><option>その他</option></select></label><label><span>分類 *</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="important-check"><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/><span className="fake-check">{important&&<Check/>}</span>重要な会議</label><label className="wide"><span>議題 *</span><input autoFocus required placeholder="例：週次進捗ミーティング" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="wide"><span>メモ</span><textarea rows={5} placeholder="決定事項や重要なポイントを記録..." value={memo} onChange={e=>setMemo(e.target.value)}/></label><label className="wide"><span>タグ <small>カンマ区切り</small></span><input placeholder="プロジェクトA, 要確認" value={tags} onChange={e=>setTags(e.target.value)}/></label></div><EditorList title="関連リンク" onAdd={()=>setLinks([...links,{id:crypto.randomUUID(),title:"",url:"",type:"document"}])}>{links.map((l,i)=><div className="editor-row" key={l.id}><input placeholder="リンクのタイトル" value={l.title} onChange={e=>setLinks(links.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><input type="url" placeholder="https://..." value={l.url} onChange={e=>setLinks(links.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/><select value={l.type} onChange={e=>setLinks(links.map((x,n)=>n===i?{...x,type:e.target.value as LinkType}:x))}><option value="document">資料</option><option value="teams">Teams</option><option value="other">その他</option></select><button type="button" onClick={()=>setLinks(links.filter((_,n)=>n!==i))}><Trash2/></button></div>)}</EditorList><EditorList title="自分のタスク" onAdd={()=>setTasks([...tasks,{id:crypto.randomUUID(),title:"",completed:false}])}>{tasks.map((t,i)=><div className="editor-row task-editor" key={t.id}><input placeholder="タスクの内容" value={t.title} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><input type="date" value={t.dueDate??""} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,dueDate:e.target.value}:x))}/><button type="button" onClick={()=>setTasks(tasks.filter((_,n)=>n!==i))}><Trash2/></button></div>)}</EditorList></div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>キャンセル</button><button className="button primary" type="submit">{meeting?"変更を保存":"会議を保存"}</button></div></form></div>
}
function EditorList({title,onAdd,children}:{title:string;onAdd:()=>void;children:React.ReactNode}){return <section className="editor-list"><div><h3>{title}</h3><button type="button" onClick={onAdd}><Plus/>追加</button></div>{children}</section>}
