"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, CircleAlert, Clock3, Download, FileText, Filter, LayoutList, Menu, Plus, Search, Settings, Star, Tags, Upload, Users, X } from "lucide-react";
import { repository } from "@/data/repository";
import { Category, Filters, Meeting, MeetingTask, View } from "@/types";
import MeetingCard from "./MeetingCard";
import MeetingPanel from "./MeetingPanel";
import MeetingForm from "./MeetingForm";

const blankFilters:Filters={category:"",place:"",from:"",to:"",important:false,hasTasks:false,incomplete:false};
const nav=[
  ["all","すべて",LayoutList],["today","今日",CalendarDays],["week","今週",Clock3],["tasks","自分のタスク",CheckCircle2],
  ["incomplete","未完了タスク",CircleAlert],["important","重要",Star],["categories","分類",Tags],["settings","設定",Settings]
] as const;
const localDate=(d=new Date())=>{const o=d.getTimezoneOffset(); return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};

export default function MeetingHub(){
  const [meetings,setMeetings]=useState<Meeting[]>([]),[categories,setCategories]=useState<Category[]>([]),[ready,setReady]=useState(false);
  const [view,setView]=useState<View>("all"),[query,setQuery]=useState(""),[filters,setFilters]=useState(blankFilters),[filterOpen,setFilterOpen]=useState(false),[sidebar,setSidebar]=useState(false);
  const [selected,setSelected]=useState<Meeting|null>(null),[editing,setEditing]=useState<Meeting|null|undefined>(undefined);
  const fileRef=useRef<HTMLInputElement>(null),csvRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{setMeetings(repository.loadMeetings());setCategories(repository.loadCategories());setReady(true)},[]);
  useEffect(()=>{if(ready) repository.saveMeetings(meetings)},[meetings,ready]);
  useEffect(()=>{if(ready) repository.saveCategories(categories)},[categories,ready]);
  const today=localDate(); const weekStart=(()=>{const d=new Date(today+"T12:00:00");d.setDate(d.getDate()-((d.getDay()+6)%7));return localDate(d)})(); const weekEnd=(()=>{const d=new Date(weekStart+"T12:00:00");d.setDate(d.getDate()+6);return localDate(d)})();
  const visible=useMemo(()=>meetings.filter(m=>{
    const hay=[m.title,m.memo,m.category,...m.tags,...m.tasks.map(t=>t.title)].join(" ").toLowerCase();
    const q=!query||hay.includes(query.toLowerCase()); const v=view==="all"||view==="categories"||view==="settings"||view==="tasks"||view==="today"&&m.date===today||view==="week"&&m.date>=weekStart&&m.date<=weekEnd||view==="important"&&m.important||view==="incomplete"&&m.tasks.some(t=>!t.completed);
    return q&&v&&(!filters.category||m.category===filters.category)&&(!filters.place||m.place===filters.place)&&(!filters.from||m.date>=filters.from)&&(!filters.to||m.date<=filters.to)&&(!filters.important||m.important)&&(!filters.hasTasks||m.tasks.length>0)&&(!filters.incomplete||m.tasks.some(t=>!t.completed));
  }).sort((a,b)=>b.date.localeCompare(a.date)),[meetings,query,filters,view,today,weekStart,weekEnd]);
  const incomplete=meetings.flatMap(m=>m.tasks).filter(t=>!t.completed).length, weekly=meetings.filter(m=>m.date>=weekStart&&m.date<=weekEnd).length, important=meetings.filter(m=>m.important).length;
  const save=(m:Meeting)=>{setMeetings(x=>x.some(i=>i.id===m.id)?x.map(i=>i.id===m.id?m:i):[m,...x]);setEditing(undefined);setSelected(m)};
  const remove=(id:string)=>{if(confirm("この会議を削除しますか？")){setMeetings(x=>x.filter(m=>m.id!==id));setSelected(null)}};
  const toggleTask=(mid:string,tid:string)=>setMeetings(x=>x.map(m=>m.id===mid?{...m,tasks:m.tasks.map(t=>t.id===tid?{...t,completed:!t.completed}:t),updatedAt:new Date().toISOString()}:m));
  const download=()=>{const blob=new Blob([repository.exportData(meetings,categories)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`meeting-hub-${today}.json`;a.click();URL.revokeObjectURL(a.href)};
  const importCsv=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=repository.parseCsv(await f.text(),categories);setMeetings(x=>[...d.meetings,...x]);setCategories(d.categories);alert(`${d.meetings.length}件を取り込みました`)}catch{alert("CSVを読み込めませんでした")}e.target.value=""};
  const importJson=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=repository.parseImport(await f.text());setMeetings(d.meetings);setCategories(d.categories);alert("データを復元しました") }catch{alert("有効なMeeting HubのJSONファイルを選択してください") }e.target.value=""};
  const activeFilters=Object.values(filters).filter(Boolean).length;
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?"open":""}`}><div className="brand"><span className="brand-mark"><CalendarDays size={21}/></span><span>Meeting Hub</span><button className="mobile-close" onClick={()=>setSidebar(false)}><X/></button></div><nav>{nav.map(([id,label,Icon],i)=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setSidebar(false)}}><Icon size={19}/><span>{label}</span>{id==="incomplete"&&incomplete>0&&<b>{incomplete}</b>}{i===2&&<span className="nav-rule"/>}</button>)}</nav><div className="sidebar-foot"><div className="avatar">YT</div><div><strong>ようこそ</strong><small>ローカルワークスペース</small></div></div></aside>
    <main><header><button className="menu-btn" onClick={()=>setSidebar(true)}><Menu/></button><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="会議、メモ、タスクを検索..."/><kbd>⌘ K</kbd></div><div className="header-actions"><button className={`button secondary ${filterOpen?"selected":""}`} onClick={()=>setFilterOpen(!filterOpen)}><Filter size={17}/>フィルター{activeFilters>0&&<i>{activeFilters}</i>}</button><button className="button primary" onClick={()=>setEditing(null)}><Plus size={18}/>会議を追加</button></div></header>
      <div className="content"><div className="page-title"><div><p className="eyebrow">WORKSPACE / MEETINGS</p><h1>{view==="tasks"?"自分のタスク":view==="today"?"今日の会議":view==="week"?"今週の会議":view==="important"?"重要な会議":view==="incomplete"?"未完了タスクのある会議":"会議一覧"}</h1><p>{view==="tasks"?"すべての会議から、あなたのアクションを集約しています。":"会議の記録、関連資料、次のアクションをひとつの場所に。"}</p></div><span className="date-chip"><CalendarDays size={15}/>{new Intl.DateTimeFormat("ja-JP",{month:"long",day:"numeric",weekday:"short"}).format(new Date())}</span></div>
      {filterOpen&&<FilterBar filters={filters} setFilters={setFilters} categories={categories}/>} 
      <section className="summaries"><Summary label="今週の会議" value={weekly} icon={<CalendarDays/>} tone="blue" onClick={()=>setView("week")}/><Summary label="未完了タスク" value={incomplete} icon={<CircleAlert/>} tone="amber" onClick={()=>setView("incomplete")}/><Summary label="重要" value={important} icon={<Star/>} tone="rose" onClick={()=>setView("important")}/></section>
      {view==="tasks"?<TaskView meetings={meetings} toggle={toggleTask} open={setSelected}/>:view==="settings"?<SettingsView meetings={meetings} categories={categories} setCategories={setCategories} download={download} fileRef={fileRef} csvRef={csvRef}/>:<section className="list-section"><div className="list-head"><div><h2>{view==="all"?"最近の会議":"該当する会議"}</h2><span>{visible.length}件</span></div><button className="sort">日付順 <ChevronRight size={15}/></button></div><div className="meeting-list">{visible.map(m=><MeetingCard key={m.id} meeting={m} category={categories.find(c=>c.id===m.category)} onClick={()=>setSelected(m)}/>)}{visible.length===0&&<div className="empty"><Search/><h3>会議が見つかりません</h3><p>検索語やフィルター条件を変更してください。</p></div>}</div></section>}
      </div>
    </main>
    {selected&&<MeetingPanel meeting={meetings.find(m=>m.id===selected.id)??selected} category={categories.find(c=>c.id===selected.category)} onClose={()=>setSelected(null)} onEdit={m=>setEditing(m)} onDelete={remove} onToggleTask={tid=>toggleTask(selected.id,tid)}/>} 
    {editing!==undefined&&<MeetingForm meeting={editing} categories={categories} onClose={()=>setEditing(undefined)} onSave={save}/>} 
    <input hidden type="file" accept="application/json" ref={fileRef} onChange={importJson}/>
    <input hidden type="file" accept=".csv,text/csv" ref={csvRef} onChange={importCsv}/>
  </div>
}
function Summary({label,value,icon,tone,onClick}:{label:string;value:number;icon:React.ReactNode;tone:string;onClick:()=>void}){return <button className="summary" onClick={onClick}><span className={`summary-icon ${tone}`}>{icon}</span><span><small>{label}</small><strong>{value}</strong></span><ChevronRight/></button>}
function FilterBar({filters,setFilters,categories}:{filters:Filters;setFilters:(f:Filters)=>void;categories:Category[]}){return <div className="filter-bar"><label>期間<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><span>〜</span><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">すべての分類</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={filters.place} onChange={e=>setFilters({...filters,place:e.target.value})}><option value="">すべての場所</option><option>Teams</option><option>対面</option><option>その他</option></select>{[["important","重要のみ"],["hasTasks","タスクあり"],["incomplete","未完了あり"]].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={Boolean(filters[k as keyof Filters])} onChange={e=>setFilters({...filters,[k]:e.target.checked})}/>{l}</label>)}<button onClick={()=>setFilters(blankFilters)}>クリア</button></div>}
function TaskView({meetings,toggle,open}:{meetings:Meeting[];toggle:(m:string,t:string)=>void;open:(m:Meeting)=>void}){const rows=meetings.flatMap(m=>m.tasks.map(t=>({m,t})));return <section className="task-board">{[false,true].map(done=><div key={String(done)}><div className="task-title"><h2>{done?"完了":"未完了"}</h2><span>{rows.filter(x=>x.t.completed===done).length}</span></div>{rows.filter(x=>x.t.completed===done).map(({m,t})=><div className={`task-row ${done?"done":""}`} key={t.id}><button className="task-check" onClick={()=>toggle(m.id,t.id)}>{t.completed?<CheckCircle2/>:<span/>}</button><button className="task-main" onClick={()=>open(m)}><strong>{t.title}</strong><small>{m.date.slice(5).replace("-","/")} ・ {m.title}{t.dueDate&&`　期限 ${t.dueDate.slice(5).replace("-","/")}`}</small></button><ChevronRight/></div>)}</div>)}</section>}
function SettingsView({meetings,categories,setCategories,download,fileRef,csvRef}:{meetings:Meeting[];categories:Category[];setCategories:(c:Category[])=>void;download:()=>void;fileRef:React.RefObject<HTMLInputElement|null>;csvRef:React.RefObject<HTMLInputElement|null>}){const [name,setName]=useState("");return <section className="settings-card"><h2>設定・データ管理</h2><p>分類の追加や、ローカルデータのバックアップができます。</p><h3>分類</h3><div className="category-settings">{categories.map(c=><span key={c.id}>{c.name}<button aria-label="削除" onClick={()=>setCategories(categories.filter(x=>x.id!==c.id))}>×</button></span>)}</div><div className="add-category"><input placeholder="新しい分類名" value={name} onChange={e=>setName(e.target.value)}/><button className="button primary" onClick={()=>{if(name.trim()){setCategories([...categories,{id:crypto.randomUUID(),name:name.trim(),color:"blue"}]);setName("")}}}><Plus size={17}/>追加</button></div><h3>バックアップ</h3><div className="backup-actions"><button className="button secondary" onClick={()=>csvRef.current?.click()}><Upload size={17}/>CSVインポート</button><button className="button secondary" onClick={download}><Download size={17}/>JSONエクスポート</button><button className="button secondary" onClick={()=>fileRef.current?.click()}><Upload size={17}/>JSONインポート</button><span>{meetings.length}件の会議を保存中</span></div></section>}
