import { useState } from "react";
import { CheckCircle2, ChevronDown, ChevronRight, Circle, Clock3, TriangleAlert, FileText, MapPin, MessageSquare, NotebookText, Star } from "lucide-react";
import { Category, Meeting } from "@/types";
import { parseIsoDate, timeRange, weekdayLabel, weekdayOf } from "@/lib/date";
import { Conflict, describeConflict } from "@/lib/conflicts";
import { groupLinksForDisplay, LinkGroup } from "@/lib/links";
import LinkChooser from "./LinkChooser";
import { isOnsite } from "@/lib/places";
const MAX_LINKS = 4;
export default function MeetingCard({meeting:m,category,dayStart=false,conflicts=[],onClick}:{meeting:Meeting;category?:Category;dayStart?:boolean;conflicts?:Conflict[];onClick:()=>void}){

 const groups=groupLinksForDisplay(m.links),[chooser,setChooser]=useState<LinkGroup|null>(null);
 const memo=m.memo?.trim()??"";
 const done=m.tasks.filter(t=>t.completed).length, d=parseIsoDate(m.date), wd=weekdayOf(m.date), time=timeRange(m);
 // リンクをカード内に置くため、カード自体は button ではなく role="button" の div にする（button 内に a は置けない）
 return <div className={`meeting-card ${dayStart?"day-start":""} ${isOnsite(m.place)?"onsite":""}`} role="button" tabIndex={0} onClick={onClick} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onClick()}}}><div className="card-date"><span className="card-month">{d.getMonth()+1}月</span><div className="card-day"><strong>{d.getDate()}</strong><span className={wd===0?"sun":wd===6?"sat":""}>({weekdayLabel(m.date)})</span></div></div><div className="card-body"><div className="card-title"><h3>{m.title}</h3>{m.important&&<Star className="star" fill="currentColor" size={17}/>}</div><div className="badges"><span className={`badge ${category?.color??"slate"}`}>{category?.name??m.category}</span>{time&&<span className="place time"><Clock3 size={14}/>{time}</span>}{conflicts.length>0&&<span className="conflict-badge" title={conflicts.map(describeConflict).join("\n")}><TriangleAlert size={13}/>{conflicts[0].reason==="time"?"時間重複":"重複の可能性"}：{conflicts[0].meeting.title}{conflicts.length>1&&` 他${conflicts.length-1}件`}</span>}{isOnsite(m.place)?<span className="place onsite" title="対面（移動が必要）"><MapPin size={14}/>{m.place}<em>移動あり</em></span>:<span className="place"><MapPin size={14}/>{m.place}</span>}{memo&&<span className="memo-badge" title={memo.length>300?`${memo.slice(0,300)}…`:memo}><NotebookText size={13}/>メモあり</span>}{m.tags.slice(0,1).map(t=><span className="tag" key={t}>#{t}</span>)}</div></div><div className={`card-meta ${m.links.length?"":"no-links"}`}><div className="card-links">{groups.length>0&&<div className="chip-grid">{groups.slice(0,MAX_LINKS).map(g=>{const icon=g.type==="teams"?<MessageSquare size={14}/>:<FileText size={14}/>,l=g.items[0];return g.items.length===1?<a key={l.id} className={`link-chip ${l.type}`} href={l.url} target="_blank" rel="noreferrer" title={`${l.title}\n${l.url}`} onClick={e=>e.stopPropagation()}>{icon}<span>{l.title}</span></a>:<button type="button" key={g.title} className={`link-chip multi ${g.type}`} title={`${g.title}：${g.items.length}件（クリックして選択）`} onClick={e=>{e.stopPropagation();setChooser(g)}} onKeyDown={e=>e.stopPropagation()}>{icon}<span>{g.title}</span><b className="chip-count">{g.items.length}</b><ChevronDown size={13}/></button>})}</div>}{groups.length>MAX_LINKS&&<span className="link-more">+{groups.length-MAX_LINKS}</span>}{m.links.length===0&&<span className="link-none">リンクなし</span>}</div><span className={`task-status ${m.tasks.length?"has":""}`}>{m.tasks.length&&done===m.tasks.length?<CheckCircle2 size={17}/>:<Circle size={17}/>} {m.tasks.length?`${done}/${m.tasks.length} 完了`:"タスクなし"}</span></div><ChevronRight className="card-arrow"/>{chooser&&<LinkChooser group={chooser} onClose={()=>setChooser(null)}/>}</div>
}
