import { useState } from "react";
import { Calendar, CheckCircle2, ClipboardPaste, Clock3, Circle, ExternalLink, FileText, Link2, Mail, MapPin, MessageSquare, Pencil, Star, Trash2, X } from "lucide-react";
import { Category, Meeting } from "@/types";
import { timeRange, weekdayLabel } from "@/lib/date";
import { isOnsite } from "@/lib/places";
import { linksFromText, mailUrlFromText, numberedLinks, readClipboardText } from "@/lib/links";
export default function MeetingPanel({meeting:m,category,onClose,onEdit,onDelete,onToggleTask,onUpdate}:{meeting:Meeting;category?:Category;onClose:()=>void;onEdit:(m:Meeting)=>void;onDelete:(id:string)=>void;onToggleTask:(id:string)=>void;onUpdate:(m:Meeting)=>void}){
 const [note,setNote]=useState("");
 // 編集画面を開かずに、クリップボードの URL から名称・種類を判定してリンクを追加する
 const pasteLinks=async()=>{const text=await readClipboardText(),mail=mailUrlFromText(text),added=linksFromText(text,m.links);if(!added.length&&!mail){setNote("クリップボードに新しい URL がありません");return}onUpdate({...m,links:[...m.links,...added],...(mail&&{inviteMail:mail}),updatedAt:new Date().toISOString()});setNote(`${[...added.map(l=>l.title),...(mail?["案内メール"]:[])].map(t=>`「${t}」`).join("")}を追加しました`)};
 const [mailNote,setMailNote]=useState("");
 const pasteMail=async()=>{const url=mailUrlFromText(await readClipboardText());if(!url){setMailNote("クリップボードに Outlook のメールリンクがありません");return}onUpdate({...m,inviteMail:url,updatedAt:new Date().toISOString()});setMailNote("案内メールを設定しました")};
 return <div className="overlay" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="detail-panel"><div className="panel-top"><span>会議の詳細</span><button onClick={onClose}><X/></button></div><div className="panel-content"><div className="detail-heading"><div className="badges"><span className={`badge ${category?.color}`}>{category?.name??m.category}</span>{m.important&&<span className="important-label"><Star size={14} fill="currentColor"/>重要</span>}</div><h2>{m.title}</h2><div className="detail-meta"><span><Calendar/>{m.date.replaceAll("-","/")} ({weekdayLabel(m.date)})</span>{m.startTime&&<span><Clock3/>{timeRange(m)}</span>}<span className={isOnsite(m.place)?"onsite":""}><MapPin/>{m.place}{isOnsite(m.place)&&<em>移動あり</em>}</span></div></div><DetailSection title="関連リンク" icon={<Link2/>} action={<button className="section-action" onClick={pasteLinks} title="コピーした URL から名称と種類を自動判定して追加"><ClipboardPaste size={15}/>クリップボードから追加</button>}>{note&&<p className="paste-note">{note}</p>}{m.links.length?numberedLinks(m.links).map(({link:l,label})=><a className="link-card" href={l.url} target="_blank" rel="noreferrer" key={l.id} title={l.url}><span className={l.type}>{l.type==="teams"?<MessageSquare/>:<FileText/>}</span><strong>{label}</strong><ExternalLink/></a>):<p className="muted">関連リンクはありません</p>}</DetailSection><DetailSection title="案内メール" icon={<Mail/>} action={<button className="section-action" onClick={pasteMail} title="Outlook でコピーしたメールのリンクを設定"><ClipboardPaste size={15}/>クリップボードから{m.inviteMail?"差し替え":"追加"}</button>}>{mailNote&&<p className="paste-note">{mailNote}</p>}{m.inviteMail?<a className="link-card" href={m.inviteMail} target="_blank" rel="noreferrer" title={m.inviteMail}><span className="mail"><Mail/></span><strong>案内メールを開く</strong><ExternalLink/></a>:<p className="muted">案内メールはありません</p>}</DetailSection><DetailSection title="メモ" icon={<FileText/>}><div className="memo-box">{m.memo||<span className="muted">メモはありません</span>}</div></DetailSection><DetailSection title="自分のタスク" icon={<CheckCircle2/>}><div className="detail-tasks">{m.tasks.length?m.tasks.map(t=><button className={t.completed?"done":""} key={t.id} onClick={()=>onToggleTask(t.id)}>{t.completed?<CheckCircle2/>:<Circle/>}<span><strong>{t.title}</strong>{t.dueDate&&<small>期限 {t.dueDate.replaceAll("-","/")}</small>}</span></button>):<p className="muted">タスクはありません</p>}</div></DetailSection>{m.tags.length>0&&<div className="detail-tags">{m.tags.map(t=><span key={t}>#{t}</span>)}</div>}</div><div className="panel-actions"><button className="danger-icon" onClick={()=>onDelete(m.id)}><Trash2/></button><button className="button primary" onClick={()=>onEdit(m)}><Pencil size={17}/>編集する</button></div></aside></div>
}
function DetailSection({title,icon,action,children}:{title:string;icon:React.ReactNode;action?:React.ReactNode;children:React.ReactNode}){return <section className="detail-section"><h3>{icon}{title}{action}</h3>{children}</section>}
